/****** Script for SelectTopNRows command from SSMS  ******/
SELECT TOP (1000) [ID]
      ,[Created_DTS]
	  ,[Run_Number]
      ,[Generation]
      ,[Generations_Completed_This_Session]
      ,[BestIndividual_ID]
	  ,[Diversity]
	  ,[Diverse_Clusters]
      ,[BestIndividual_Training_Score]
      ,[BestIndividual_Training_Error] 
      ,[Average_Training_Error]
      ,[Standard_Deviation]
      ,[BestIndividual_Test_Score]
      ,[Number_Of_Training_Cases]
      ,[Number_Of_Test_Cases]
      ,[Best_Genome]
      ,[Population_Size]
      ,[Alternation_Rate]
      ,[Uniform_Mutation_Rate]
      ,[Example_Case_Max_Length]
      ,[Example_Case_Upper_Range]
      ,[Tempareture]
      ,[BestIndividual_Prev_Training_Error]
      ,[Stalled_Count]
      ,[Cool_Down_Count]
      ,[Include_Best_Individual_In_Breeding_Pool]
      ,[BestIndividual_Training_Effort]
	  ,ABS([BestIndividual_Training_Error] - [BestIndividual_Prev_Training_Error]) AS Delta_Error
  FROM [SOS].[dbo].[ProgressLog] (NOLOCK)
--  where [Stalled_Count] < 2
  Order by [Created_DTS] Desc
